FROM node:18

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    curl -s https://dl.k6.io/key.gpg | gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list && \
    apt-get update && apt-get install -y k6 && \
    rm -rf /var/lib/apt/lists/*
    

COPY --chown=node:node tests/package*.json ./

RUN npm ci

COPY --chown=node:node tests/lib ./lib
COPY --chown=node:node tests/.env ./lib
COPY --chown=node:node tests/feed.js ./feed.js
COPY --chown=node:node tests/profile.js ./profile.js

ENV SERVER_ENDPOINT=http://host.docker.internal:3000

CMD ["sh", "-c", "npm run test:profile && npm run test:feed"]

